# Generated by Django 2.1.3 on 2018-12-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('somebody', models.CharField(max_length=30)),
                ('motion', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('gender', models.CharField(max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/icon')),
                ('date', models.DateField()),
            ],
        ),
    ]
