# Generated by Django 2.1.3 on 2018-12-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='date1',
        ),
    ]
